### ISSUE TITLE
Feat: Créer la landing page

### ISSUE THREAD

**Issue by MrAnyx** [Buissartt/Laoutira#2]
## Description

Créer la landing selon la maquette qui nous a été envoyé. [Lien](https://laoutira.mystrikingly.com/)

## Eléments attendus

Avoir une version fonctionnelle de la landing page

## Liens de dépendances (Issue(s) nécessaire(s) pour la réalisation de celle-ci)

- [ ] #6 - Feat: Créer la page de connexion 
- [ ] #3 - Feat: Créer le système d'inscription 
- [ ] #7 - Feat: Créer les entités complémentaires 
- [x] #8 - Feat: Créer le template de base

## Screenshot (optionnel)

![screencapture-laoutira-mystrikingly-2020-12-17-18_41_49](https://user-images.githubusercontent.com/44176707/102523266-9214ad00-4097-11eb-883f-1b3736f8bb46.png)

## Tâches

- [x] Navbar
- [x] Jumbotron avec Image de fond
- [x] Section "Comment ça marche ?"
- [x] Jumbotron "Trouve ta ville idéale !"
- [x] Temoignages
- [x] Liens de blogs
- [x] Section questionnaire
- [x] Les réseaux sociaux
- [x] Inscription
- [x] Footer

**Comment by MrAnyx** [comment]
Done !
